name: number_baseball_webview
description: "Flutter shell that wraps the deployed Number Baseball React app in a WebView."
publish_to: "none"
version: 0.1.2+3

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true
